M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-15T04:49:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-15T04:49:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.099
%
G90
G05
T1
X133.9Y-64.9
X133.9Y-93.1
T2
X133.59Y-73.25
X133.59Y-84.75
M30
