M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-03-23T11:12:44-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-23T11:12:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1220
%
G90
G05
T1
X5.2165Y-2.5551
X5.2165Y-3.6654
T2
X5.2594Y-2.8839
X5.2594Y-3.3366
M30
