M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-03-23T10:20:48-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-23T10:20:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1160
%
G90
G05
T1
X5.8811Y-3.5522
X6.0061Y-2.3572
T2
X5.7Y-2.405
X6.57Y-2.405
M30
